language: python
python:
  - "2.7.13"

services:
  - docker

install: 
  - pip install -r requirements.txt
  - pip install coverage
  - docker build -t app-server ./
  - mkdir shared

script:
  - python src/tests/test_index.py
