language: python
python:
  - "2.7.13"

services:
  - docker

install: 
  - pip install -r requirements.txt
  - pip install coverage
  - docker build -t app-server
  - mkdir shared

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
#  - docker run $ci_env -v "$PWD/shared:/app/shared" -p 5000:5000 app-server sh test-cover-enviar-en-docker-appserver.sh
#  - bash <(curl -s https://codecov.io/bash) -f shared/coverage.json -t 9b56dd78-a3ab-4a7d-a7ea-bd326e5348ad
#  - bash <(curl -s https://codecov.io/bash) -f shared/coverage.xml -t 9b56dd78-a3ab-4a7d-a7ea-bd326e5348ad
