language: python
python:
  - "2.7.13"

services:
  - docker

install: 
  - pip install -r requirements.txt
  - pip install coverage
  - docker build -t app-server ./
  - mkdir shared

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env -v "$PWD/shared:/app/shared" -p 5000:5000 app-server sh test-cover-enviar-en-docker-appserver.sh
  - bash <(curl -s https://codecov.io/bash) -f shared/coverage.xml -t f5b97a7b-8502-4c9d-97cc-7099b9e15b8d
